import { ColumnStats, FileType, FilterCondition, QueryState } from '../types';
import { generateSQL } from './sqlGenerator';

function formatPySparkFilter(condition: FilterCondition, colStatsMap: Map<string, ColumnStats>): string {
  const colStat = colStatsMap.get(condition.column);
  const isNumeric = colStat?.type === 'number';
  const val = condition.value.trim();

  if (condition.operator === 'IS NULL') {
    return `col("${condition.column}").isNull()`;
  }
  if (condition.operator === 'IS NOT NULL') {
    return `col("${condition.column}").isNotNull()`;
  }
  if (condition.operator === 'CONTAINS') {
    return `col("${condition.column}").contains("${val.replace(/"/g, '\\"')}")`;
  }
  if (condition.operator === 'STARTS_WITH') {
    return `col("${condition.column}").startswith("${val.replace(/"/g, '\\"')}")`;
  }
  if (condition.operator === 'ENDS_WITH') {
    return `col("${condition.column}").endswith("${val.replace(/"/g, '\\"')}")`;
  }
  if (condition.operator === 'IN') {
    const items = val
      .split(',')
      .map((item) => item.trim())
      .map((item) => (isNumeric && !isNaN(Number(item)) ? item : `"${item.replace(/"/g, '\\"')}"`))
      .join(', ');
    return `col("${condition.column}").isin([${items}])`;
  }

  const pyOp = condition.operator === '=' ? '==' : condition.operator;
  if (isNumeric && !isNaN(Number(val))) {
    return `col("${condition.column}") ${pyOp} ${val}`;
  }

  return `col("${condition.column}") ${pyOp} "${val.replace(/"/g, '\\"')}"`;
}

export function generatePySparkCode(
  queryState: QueryState,
  allColumnStats: ColumnStats[],
  fileType: FileType = 'csv',
  fileName = 'dataset.csv'
): string {
  const { selectedColumns, filters, groupBy, orderBy, limit, sparkConfig } = queryState;
  const colStatsMap = new Map<string, ColumnStats>(allColumnStats.map((c) => [c.name, c]));

  const appName = sparkConfig.appName || 'DataAnalysisJob';
  const inputPath = sparkConfig.inputPath || `./data/${fileName}`;
  const isSparkSql = sparkConfig.mode === 'spark_sql';

  // If Spark SQL mode is selected
  if (isSparkSql) {
    const rawSql = generateSQL({ ...queryState, dialect: 'ansi' }, allColumnStats);
    const indentedSql = rawSql
      .split('\n')
      .map((line) => `        ${line}`)
      .join('\n');

    let readCode = '';
    if (fileType === 'csv') {
      readCode = `df = (
    spark.read
    .option("header", "true")
    .option("inferSchema", "true")
    .csv("${inputPath}")
)`;
    } else if (fileType === 'xlsx' || fileType === 'xls') {
      readCode = `import pandas as pd

# Load Excel with pandas and bridge to Spark DataFrame
pdf = pd.read_excel("${inputPath}")
df = spark.createDataFrame(pdf)`;
    } else {
      readCode = `df = (
    spark.read
    .option("multiline", "true")
    .json("${inputPath}")
)`;
    }

    return `"""
PySpark Script - Spark SQL Mode
Generated by DataInsight Studio
"""

from pyspark.sql import SparkSession

def main():
    # 1. Initialize SparkSession
    spark = (
        SparkSession.builder
        .appName("${appName}")
        .master("local[*]")
        .getOrCreate()
    )

    # 2. Ingest Data
    ${readCode}

    # 3. Register as Temporary View
    df.createOrReplaceTempView("${queryState.tableName || 'my_table'}")

    # 4. Execute Spark SQL Query
    query = """
${indentedSql}
    """
    result_df = spark.sql(query)

    # 5. Output Results
    print("=== Query Results ===")
    result_df.show(${limit || 20}, truncate=False)
    result_df.printSchema()

    spark.stop()

if __name__ == "__main__":
    main()
`;
  }

  // DataFrame API Mode
  let neededFunctions = new Set<string>(['col']);

  let readerCode = '';
  if (fileType === 'csv') {
    readerCode = `df = (
        spark.read
        .option("header", "true")
        .option("inferSchema", "true")
        .csv("${inputPath}")
    )`;
  } else if (fileType === 'xlsx' || fileType === 'xls') {
    readerCode = `# Read Excel with pandas and create Spark DataFrame
    import pandas as pd
    pdf = pd.read_excel("${inputPath}")
    df = spark.createDataFrame(pdf)`;
  } else {
    readerCode = `df = (
        spark.read
        .option("multiline", "true")
        .json("${inputPath}")
    )`;
  }

  const pipelineSteps: string[] = [];

  // Filter Step
  if (filters.length > 0) {
    let filterExpr = '';
    filters.forEach((f, idx) => {
      const cond = formatPySparkFilter(f, colStatsMap);
      if (idx === 0) {
        filterExpr = `(${cond})`;
      } else {
        const pyLogical = f.combinator === 'AND' ? '&' : '|';
        filterExpr = `${filterExpr} ${pyLogical} (${cond})`;
      }
    });

    pipelineSteps.push(`    # Apply Filters
    df = df.filter(${filterExpr})`);
  }

  // Group By & Aggregation
  let hasAggregations = false;
  const nonAggCols: string[] = [];
  const aggExprs: string[] = [];

  selectedColumns.forEach((sc) => {
    if (sc.aggregation && sc.aggregation !== 'NONE') {
      hasAggregations = true;
      let funcName = sc.aggregation.toLowerCase();
      if (sc.aggregation === 'COUNT_DISTINCT') {
        funcName = 'countDistinct';
        neededFunctions.add('countDistinct');
      } else {
        neededFunctions.add(funcName);
      }

      const aliasStr = sc.alias ? sc.alias.trim() : `${funcName}_${sc.column}`;
      aggExprs.push(`${funcName}("${sc.column}").alias("${aliasStr}")`);
    } else {
      nonAggCols.push(sc.column);
    }
  });

  const finalGroupBy = Array.from(new Set([...groupBy, ...(hasAggregations ? nonAggCols : [])]));

  if (hasAggregations && finalGroupBy.length > 0) {
    const groupCols = finalGroupBy.map((c) => `"${c}"`).join(', ');
    const aggsJoined = aggExprs.join(', ');
    pipelineSteps.push(`    # Group by and Aggregate
    df = df.groupBy(${groupCols}).agg(
        ${aggsJoined}
    )`);
  } else if (selectedColumns.length > 0 && !hasAggregations) {
    // Standard Column Selection
    const selectArgs = selectedColumns.map((sc) => {
      if (sc.alias && sc.alias.trim()) {
        return `col("${sc.column}").alias("${sc.alias.trim()}")`;
      }
      return `"${sc.column}"`;
    });
    pipelineSteps.push(`    # Select Columns
    df = df.select(${selectArgs.join(', ')})`);
  }

  // Ordering
  if (orderBy.length > 0) {
    const orderArgs = orderBy.map((o) => {
      if (o.direction === 'DESC') {
        neededFunctions.add('desc');
        return `desc("${o.column}")`;
      } else {
        neededFunctions.add('asc');
        return `asc("${o.column}")`;
      }
    });
    pipelineSteps.push(`    # Order By
    df = df.orderBy(${orderArgs.join(', ')})`);
  }

  // Limit
  if (limit && limit > 0) {
    pipelineSteps.push(`    # Limit Output
    df = df.limit(${limit})`);
  }

  // Output Action
  let actionCode = '';
  switch (sparkConfig.outputAction) {
    case 'parquet':
      actionCode = `    # Write to Parquet
    output_target = "${sparkConfig.outputPath || './output/processed_data.parquet'}"
    df.write.mode("overwrite").parquet(output_target)
    print(f"Dataset successfully saved to {output_target}")`;
      break;
    case 'csv':
      actionCode = `    # Write to CSV
    output_target = "${sparkConfig.outputPath || './output/processed_data.csv'}"
    df.write.mode("overwrite").option("header", "true").csv(output_target)
    print(f"Dataset successfully saved to {output_target}")`;
      break;
    case 'toPandas':
      actionCode = `    # Convert to pandas DataFrame for local exploration
    pdf_result = df.toPandas()
    print(pdf_result.head())`;
      break;
    case 'show':
    default:
      actionCode = `    # Display Sample Rows
    print("=== Transformed DataFrame ===")
    df.show(50, truncate=False)
    print(f"Total Rows: {df.count()}")
    df.printSchema()`;
      break;
  }

  const importList = Array.from(neededFunctions).sort().join(', ');

  return `"""
PySpark Data Transformation Script
Generated by DataInsight Studio (100% Offline)
File: ${fileName}
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import ${importList}

def run_pipeline():
    # 1. Initialize SparkSession
    spark = (
        SparkSession.builder
        .appName("${appName}")
        .master("local[*]")
        .config("spark.sql.shuffle.partitions", "4")
        .getOrCreate()
    )

    # 2. Ingest Source File
    ${readerCode}

${pipelineSteps.join('\n\n')}

    # 3. Action / Sink
${actionCode}

    # 4. Stop Spark Session
    spark.stop()

if __name__ == "__main__":
    run_pipeline()
`;
}
